spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/import_app
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-source-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB